Category branch
motuncoded/edulearning pull request #27
Opened 2024-10-19 19:27 UTC by motuncoded

Set up category page

2024-10-19 19:47 UTC, Asylcreek requested changes

2024-10-19 19:47 UTC, Asylcreek commented on src/app/categories/page.tsx
> +        <h2 className="text-4xl font-bold bg-gradient-to-r from-blue-500 via-yellow-400 to-orange-400 bg-clip-text text-transparent">
Why not `h1`?

2024-10-19 19:47 UTC, Asylcreek commented on src/app/components/Footer.tsx
> +    <h3 className="flex items-center mb-4">
This can be a `p`

2024-10-19 19:47 UTC, Asylcreek commented on src/app/components/Footer.tsx
> +      <h3 className="font-bold">Subscribe for our newsletter.</h3>
This can be a `p`

2024-10-19 19:47 UTC, Asylcreek commented on src/app/components/Footer.tsx
The use of heading tags is supposed to be hierarchical. You should not use `h2` if there is no `h1` on your page. And you should never skip a tag, meaning that if there is an `h4` on your page, there must already be an `h1`, `h2`, and `h3`

2024-10-20 07:01 UTC, motuncoded commented on src/app/categories/page.tsx
> +        <h2 className="text-4xl font-bold bg-gradient-to-r from-blue-500 via-yellow-400 to-orange-400 bg-clip-text text-transparent">
ok

2024-10-20 07:05 UTC, motuncoded commented on src/app/components/Footer.tsx
Noted...

2024-10-20 19:52 UTC, Asylcreek approved these changes

2024-10-21 05:15 UTC, merged