Art section
motuncoded/edulearning pull request #28
Opened 2024-10-31 17:09 UTC by motuncoded

This commit introduces the category section of the website and the set up of the art category page

closes #21

2024-11-01 10:29 UTC, Asylcreek requested changes

2024-11-01 10:29 UTC, Asylcreek commented on src/app/categories/category/art/Books.tsx
> +  const BOOKS_URL = "https://openlibrary.org/search.json?q=art";
Move this outside of the React function

2024-11-01 10:29 UTC, Asylcreek commented on src/app/categories/category/art/Books.tsx
> +  };
Move this inside the useEffect

2024-11-01 10:29 UTC, Asylcreek commented on src/app/json/categories.json
> +    "link": "/categories/category/art",
Why?

2024-11-01 10:29 UTC, Asylcreek commented on src/app/json/category.json
> +    "link": "/category/art",
Why?

2024-11-01 10:29 UTC, Asylcreek commented on src/app/offer.tsx
> +    <h6 className="">{description}</h6>
Are these actually headings or are you trying to avoid adding styles to a `p` tag?

2024-11-01 10:58 UTC, motuncoded commented on src/app/json/categories.json
> +    "link": "/categories/category/art",
It is because I created a layout for all categories.

2024-11-01 11:17 UTC, motuncoded commented on src/app/categories/category/art/Books.tsx
> +  const BOOKS_URL = "https://openlibrary.org/search.json?q=art";
ok

2024-11-01 11:26 UTC, motuncoded commented on src/app/categories/category/art/Books.tsx
> +  };
ok

2024-11-01 13:37 UTC, Asylcreek commented on src/app/json/categories.json
> +    "link": "/categories/category/art",
I apologise, I could have been clearer in the question.

I am trying to find out why you added the extra `/category` to the url when it was fine without it

2024-11-05 16:15 UTC, Asylcreek requested changes

2024-11-05 16:15 UTC, Asylcreek commented on src/app/categories/art/page.tsx
> +      headerIcon="&#127912;"
I do not think you are supposed to import this file into your React component like this. Please confirm from the Next docs

2024-11-11 10:20 UTC, Asylcreek requested changes

2024-11-11 10:20 UTC, Asylcreek commented on src/app/categories/art/page.tsx
> +import Layout from "../layout";
All layout files are automatically added to the children of those layouts in Next 14's app router. Can you please confirm that this is the behaviour you are actually trying to achieve? The behaviour of double nesting the layout?

2024-11-11 10:20 UTC, Asylcreek commented on src/app/categories/art/page.tsx
> +const Art: React.FC = () => {
```suggestion
const Art = () => {
```

2024-11-11 10:20 UTC, Asylcreek commented on src/app/categories/art/page.tsx
> +import Layout from "../layout";
If you actually do intend to use the layout the way it is in this file, it would be best that you move it into maybe the `components` folder or another folder entirely.

Keep in mind that this change would affect everywhere you used this pattern for the `CategoryLayout`

2024-11-11 10:20 UTC, Asylcreek commented on src/app/categories/art/Books.tsx
> +    };
Is this the intended use? You are only defining this function and not using it at all

2024-11-12 16:36 UTC, motuncoded commented on src/app/categories/art/page.tsx
> +const Art: React.FC = () => {
ok

2024-11-16 11:11 UTC, Asylcreek approved these changes

2024-11-16 11:44 UTC, merged