Hero intro section
motuncoded/edulearning pull request #6
Opened 2024-06-13 21:11 UTC by motuncoded

In this change, I create an intro section for the hero page with display of quotes.

closes #5

2024-06-14 09:02 UTC, Asylcreek commented
Please resolve the conflicts

2024-06-14 10:38 UTC, motuncoded commented
> Please resolve the conflicts

2024-06-14 10:38 UTC, motuncoded commented
It is resolved

2024-06-14 20:48 UTC, Asylcreek requested changes

2024-06-14 20:48 UTC, Asylcreek commented on src/app/page.tsx
> +
Move these into a data file

2024-06-14 20:48 UTC, Asylcreek commented on src/app/page.tsx
> +  const [quote, setQuote] = useState(quotes[currentQuote].quote);
You do not need this state

2024-06-14 20:48 UTC, Asylcreek commented on src/app/page.tsx
> +      <h3 className="max-sm:text-center max-sm:pt-4 px-2">{quote}</h3>
```suggestion
      <h3 className="max-sm:text-center max-sm:pt-4 px-2">{quotes[currentQuote].quote}</h3>
```

2024-06-14 20:48 UTC, Asylcreek commented on src/app/page.tsx
> +  const [currentQuote, setCurrentQuote] = useState(0);
A better variable name would be `quoteIndex`

2024-06-15 13:09 UTC, motuncoded commented on src/app/page.tsx
> +
ok

2024-06-16 19:34 UTC, Asylcreek approved these changes

2024-06-16 19:39 UTC, merged